[package]
name = "warplib"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
log = "0.4.14"
prometheus = "0.12.0"
warp = "0.3.1"
tokio = { version = "1.8.1", features=["full"]}
tokio-stream = "0.1.7"
tokio-util = { version = "0.6.7", features = ["io"] }
anyhow = "1.0.44"
